### ISSUE TITLE
Kerberize Cluster

### ISSUE THREAD

**Issue by xefke** [xefke/SEBC#15]

**Comment by xefke** [comment]
Successfully kerberized the nodes.
Can do kinit.
```
[root@node201 ~]# sudo -su theresa
[theresa@node201 root]$ kinit theresa
Password for theresa@XEFKE.CO.UK:
[theresa@node201 root]$ klist
Ticket cache: FILE:/tmp/krb5cc_2000
Default principal: theresa@XEFKE.CO.UK

Valid starting     Expires            Service principal
06/09/17 11:02:34  06/10/17 11:02:34  krbtgt/XEFKE.CO.UK@XEFKE.CO.UK
	renew until 06/16/17 11:02:34
```
I can also run HDFS commands.
```
[theresa@node201 root]$ hdfs dfs -ls
Found 2 items
drwx------   - theresa theresa          0 2017-06-09 10:28 .staging
drwxr-xr-x   - theresa theresa          0 2017-06-09 10:28 tgen512m
```
However, when running the terasort, I have an issue with the NameNode being in Safe mode.
```
[theresa@node201 root]$ time /opt/cloudera/parcels/CDH/bin/hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar terasort -Dmapreduce.job.maps=6 -Dmapreduce.job.reduces=6 /user/theresa/tgen512m /user/theresa/tsort512m
17/06/09 11:03:12 INFO terasort.TeraSort: starting
17/06/09 11:03:14 ERROR terasort.TeraSort: Cannot issue delegation token. Name node is in safe mode.
The reported blocks 0 needs additional 833 blocks to reach the threshold 0.9990 of total blocks 833.
The number of live datanodes 0 needs an additional 1 live datanodes to reach the minimum number 1.
Safe mode will be turned off automatically once the thresholds have been reached.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkNameNodeSafeMode(FSNamesystem.java:1463)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getDelegationToken(FSNamesystem.java:7501)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getDelegationToken(NameNodeRpcServer.java:548)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getDelegationToken(AuthorizationProviderProxyClientProtocol.java:663)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getDelegationToken(ClientNamenodeProtocolServerSideTranslatorPB.java:981)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2212)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2210)


real	0m3.161s
user	0m4.102s
sys	0m0.525s
```

I did not have the time to finish the debugging for this unfortunately.

**Comment by xefke** [comment]
Proof of kerberos install:
```
[root@node201 ~]# kadmin.local
Authenticating as principal cloudera-scm/admin@XEFKE.CO.UK with password.
kadmin.local:  list_principals
HTTP/node201.sebc@XEFKE.CO.UK
HTTP/node202.sebc@XEFKE.CO.UK
HTTP/node203.sebc@XEFKE.CO.UK
HTTP/node204.sebc@XEFKE.CO.UK
HTTP/node205.sebc@XEFKE.CO.UK
K/M@XEFKE.CO.UK
cloudera-scm/admin@XEFKE.CO.UK
hdfs/node201.sebc@XEFKE.CO.UK
hdfs/node202.sebc@XEFKE.CO.UK
hdfs/node203.sebc@XEFKE.CO.UK
hdfs/node204.sebc@XEFKE.CO.UK
hdfs/node205.sebc@XEFKE.CO.UK
hive/node201.sebc@XEFKE.CO.UK
hue/node201.sebc@XEFKE.CO.UK
jeremy@XEFKE.CO.UK
kadmin/admin@XEFKE.CO.UK
kadmin/changepw@XEFKE.CO.UK
kadmin/node201.sebc@XEFKE.CO.UK
krbtgt/XEFKE.CO.UK@XEFKE.CO.UK
mapred/node201.sebc@XEFKE.CO.UK
oozie/node201.sebc@XEFKE.CO.UK
root/admin@XEFKE.CO.UK
theresa@XEFKE.CO.UK
xefke@XEFKE.CO.UK
yarn/node201.sebc@XEFKE.CO.UK
yarn/node202.sebc@XEFKE.CO.UK
yarn/node203.sebc@XEFKE.CO.UK
yarn/node204.sebc@XEFKE.CO.UK
yarn/node205.sebc@XEFKE.CO.UK
zookeeper/node201.sebc@XEFKE.CO.UK
zookeeper/node202.sebc@XEFKE.CO.UK
zookeeper/node203.sebc@XEFKE.CO.UK
```

**Comment by xefke** [comment]
Found the issue: Made a typo in the krb5.conf file
Because a known issue, I added udp_preference_limit = 1 to the file.
But I wrongly typed udp_prefernce_limit = 1 instead

After correcting and copying the files over to each host, the issue was solved.
```
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = XEFKE.CO.UK
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 udp_preference_limit = 1

[realms]
 XEFKE.CO.UK = {
  kdc = node201.sebc
  admin_server = node201.sebc
 }

[domain_realm]
 .sebc = XEFKE.CO.UK
 sebc = XEFKE.CO.UK
```
